#!/usr/bin/env python

from sys import argv

from osgbuild.main import guess_pkg_dir
from osgbuild.fetch_sources import fetch

try:
    fetch_dir = argv[1]
except IndexError:
    fetch_dir = '.'

fetch(guess_pkg_dir(fetch_dir))

