#!/bin/bash
#
# edgmkgridmap-cron  This shell script enables the automatic use of edgmkgridmap
#
# Author:       Neha Sharma <neha@fnal.gov>
#
# chkconfig:	- 51 01
#
# description:  Enable daily run of edgmkgridmap-cron
# processname:  edgmkgridmap-cron
#

# source function library
. /etc/rc.d/init.d/functions

lockfile=/var/lock/subsys/edgmkgridmap-cron

RETVAL=0

start() {
	action $"Enabling periodic edgmkgridmap: " touch "$lockfile" 
	RETVAL=$?
}

stop() {
	action $"Disabling periodic edgmkgridmap: " rm -f "$lockfile" 
	RETVAL=$?
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop) 
	stop
	;;
  restart|force-reload)
	restart
	;;
  reload)
	;;
  condrestart)
	[ -f "$lockfile" ] && restart
	;;
  status)
	if [ -f $lockfile ]; then
		echo $"Periodic edgmkgridmap is enabled."
		RETVAL=
	else
		echo $"Periodic edgmkgridmap is disabled."
		RETVAL=3
	fi
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
	exit 1
esac

exit $RETVAL
