#!/bin/bash

sbindir=/usr/sbin
sysconfdir=/etc

rc=0
defaultconf=${sysconfdir}/gridftp-sshftp
enabledconf=/etc/grid-security/sshftp

# OSG addition: source our sysconfig file
. /usr/share/osg/sysconfig/globus-gridftp-server

/usr/libexec/globus-gridftp-sshftp-stop
${sbindir}/globus-gridftp-server-enable-sshftp -force -out $defaultconf
/usr/libexec/globus-gridftp-sshftp-start
