#!/bin/bash

usage () {
  echo "$(basename "$0") CONDOR_VERSION"
  echo
  echo "list the afs srpm location for the most recent pre-release"
  echo "for the given version of condor (X.Y.Z)"
  exit
}

[[ $1 =~ ^[1-9][0-9]*\.[0-9]+\.[0-9]+$ ]] || usage

ls -rt /p/condor/public/html/htcondor/repo/*/el7/x86_64/*/SRPMS/condor-$1-0.*.el7.src.rpm \
| tail -1

