#!/bin/bash
set -e

cd "$(dirname "$0")"

usage () {
  echo "Which condor version?"
  echo
  echo "usage: $(basename "$0") X.Y.Z"
  exit
}

if [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  VERSION=$1
  SERIES=${VERSION%.*}
  OS=el7
  SRPM=condor-$VERSION-1.${OS}.src.rpm
  PUBLIC_SRPM=/p/condor/public/html/htcondor/repo/$SERIES/$OS/x86_64/release/SRPMS/$SRPM
elif [[ $1 = /*/condor-*.src.rpm && -f $1 ]]; then
  PUBLIC_SRPM=$1
  SRPM=${1##*/}
  NV=${SRPM%-*}
  VERSION=${NV##*-}
else
  usage
fi

UPSTREAM=/p/vdt/public/html/upstream/condor/$VERSION/

if [[ ! -e $UPSTREAM/$SRPM ]]; then
  mkdir -p $UPSTREAM
  cp $PUBLIC_SRPM $UPSTREAM
fi

sha1=$(sha1sum $UPSTREAM/$SRPM | awk '{print $1}')

echo condor/$VERSION/$SRPM sha1sum=$sha1 > upstream/developer.srpm.source

