#!/bin/bash
set -e

cd "$(dirname "$0")"

usage () {
  echo "Which condor version?"
  echo
  echo "usage: $(basename "$0") X.Y.Z"
  exit
}

if [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  VERSION=$1
  SERIES=${VERSION%.*}
  SRPM=condor-$VERSION-1.src.rpm
  PUBLIC_SRPM=/p/condor/public/binaries/v$SERIES/$VERSION/$SRPM
elif [[ $1 = /*/condor-*.src.rpm && -f $1 ]]; then
  PUBLIC_SRPM=$1
  SRPM=${1##*/}
  NV=${SRPM%-*}
  VERSION=${NV##*-}
else
  usage
fi

UPSTREAM=/p/vdt/public/html/upstream/condor/$VERSION/

if [[ ! -e $UPSTREAM/$SRPM ]]; then
  mkdir -p $UPSTREAM
  cp $PUBLIC_SRPM $UPSTREAM
fi

echo condor/$VERSION/$SRPM > upstream/developer.srpm.source

