amqp:
  url: amqps://username:password@example.com/vhost
  exchange: shoveled-xrd
  topic:
  token_location: /etc/xrootd-monitoring-shoveler/token

listen:
  port: 9993
  ip: 0.0.0.0

# Where to foward udp messages, if necessary
# Multiple destinations supported
#outputs:
#  destinations:
#    - 127.0.0.1:1234

# Whether to verify the header of the packet matches XRootD's monitoring
# packet format
verify: true

# Export prometheus metrics
metrics:
  enable: true
  port: 8000

# Directory to store overflow of queue onto disk.
# The queue keeps 100 messages in memory.  If the shoveler is disconnected from the message bus,
# it will store messages over the 100 in memory onto disk into this directory.  Once the connection has been re-established
# the queue will be emptied.  The queue on disk is persistent between restarts.
config_directory: /var/spool/shoveler-queue


