#!/bin/sh


OSG_VERSION=/etc/osg-version
if [ "X$OSG_LOCATION" != "X" ]; then
    OSG_VERSION=$OSG_LOCATION/$OSG_VERSION
fi
if [ -e $OSG_VERSION ]; then
    echo -n 'OSG '
    cat $OSG_VERSION
else
    echo "Unknown OSG version"
fi

exit 0
