
%define _noarchlib %{_exec_prefix}/lib
%define dirname gums

Name: gums
Summary: Grid User Management System.  Authz for grid sites
Version: 1.3.18.002
Release: 1
License: Unknown
Group: System Environment/Daemons
BuildRequires: maven2
BuildRequires: java-devel
Requires: java
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-buildroot
BuildArch: noarch

# Tarball can be generated by doing the following:
# svn export https://svn.usatlas.bnl.gov/svn/privilege/tags/gums-core-1.3.18.002 gums-core
# tar zcf gums-core-1.3.18.002.tar.gz gums-core/
Source0: %{name}-core-%{version}.tar.gz
# svn export https://svn.usatlas.bnl.gov/svn/privilege/tags/gums-client-1.3.18.002 gums-client
# tar zcf gums-client-1.3.18.002.tar.gz gums-client
Source1: %{name}-client-%{version}.tar.gz

Patch0: gums-build.patch

%description
%{summary}

%package client
Requires: %{name} = %{version}
Group: System Environment/Daemons
Summary: Clients for GUMS

%description client
%{summary}

%prep

%setup -c -a 1
%patch0 -p0

%build

pushd gums-core
mvn -Dmaven.repo.local=/tmp/m2-repository -Dmaven.test.skip=true install
popd
pushd gums-client
mvn -Dmaven.repo.local=/tmp/m2-repository -Dmaven.test.skip=true install
popd

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT

# JARs
mkdir -p $RPM_BUILD_ROOT%{_noarchlib}/%{dirname}
mkdir -p $RPM_BUILD_ROOT%{_noarchlib}/%{dirname}/endorsed
install -m 0644 gums-client/target/lib/*.jar $RPM_BUILD_ROOT%{_noarchlib}/%{dirname}/
install -m 0644 gums-core/target/*.jar $RPM_BUILD_ROOT%{_noarchlib}/%{dirname}/

install -m 0644 gums-client/target/lib/endorsed/*.jar $RPM_BUILD_ROOT%{_noarchlib}/%{dirname}/endorsed/

# Scripts
mkdir -p $RPM_BUILD_ROOT%{_bindir}
install -m 0755 gums-client/src/main/scripts/* $RPM_BUILD_ROOT%{_bindir}/

# Configuration files
mkdir -p $RPM_BUILD_ROOT%{_sysconfdir}/%{dirname}
install -m 0644 gums-client/src/main/config/*  $RPM_BUILD_ROOT%{_sysconfdir}/%{dirname}/

# Log directory
mkdir -p $RPM_BUILD_ROOT/var/log/%{dirname}

%files
%defattr(-,root,root,-)
%{_noarchlib}/%{dirname}

%files client
%{_bindir}/*
%config(noreplace) %{_sysconfdir}/%{dirname}/gums-client.properties
%config(noreplace) %{_sysconfdir}/%{dirname}/gums-nagios.conf
%config(noreplace) %{_sysconfdir}/%{dirname}/log4j.properties
%dir /var/log/%{dirname}

%changelog
* Thu Jun 2 2011 Brian Bockelman <bbockelm@cse.unl.edu> 1.3.17-2
- Initial source RPM from GUMS website's binary tarball.

